#配置dev环境
server:
  port: 7070
spring:
  profiles: dev
  application:
    name: abcmsc-consumer-depart


eureka:
  client:
    service-url: #指定eureka服务注册中心
      defaultZone: http://localhost:8400/eureka

#开启feign对hystrix的支持
feifn:
  hystrix:
    enable: true

---
#配置test环境
server:
  port: 9090
spring:
  profiles: test
  application:
    name: abcmsc-consumer-depart


eureka:
  client:
    service-url: #指定eureka服务注册中心
      defaultZone: http://localhost:8500/eureka

#开启feign对hystrix的支持
feifn:
  hystrix:
    enable: true

