#配置dev环境
server:
  port: 8084
spring:
  profiles: dev
  application:
    name: abcmsc-provider-depart

  jpa:
    #启动时是否自动建表，默认false
    generate-ddl: true
    #是否在控制台显示sql语句，默认false
    show-sql: true
    #设置应用启动时，不重新建表
    hibernate:
      ddl-auto: none

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.106.244.80:3306/springcloud2?useUnicode=true&characterEncoding=UTF-8
    username: remote
    password: Ymx_123!


eureka:
  client:
    service-url: #指定eureka服务注册中心
      defaultZone: http://localhost:8400/eureka

---
#配置test环境
server:
  port: 8085
spring:
  profiles: dev
  application:
    name: abcmsc-provider-depart

  jpa:
    #启动时是否自动建表，默认false
    generate-ddl: true
    #是否在控制台显示sql语句，默认false
    show-sql: true
    #设置应用启动时，不重新建表
    hibernate:
      ddl-auto: none

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.106.244.80:3306/springcloud3?useUnicode=true&characterEncoding=UTF-8
    username: remote
    password: Ymx_123!


eureka:
  client:
    service-url: #指定eureka服务注册中心
      defaultZone: http://localhost:8500/eureka